# Generated by Django 5.2.6 on 2025-10-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_total_order_total_price_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
