# Generated by Django 5.2.6 on 2025-10-07 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_event_organiser_alter_ticket_attendee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location_type',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat_number',
        ),
    ]
