# Generated by Django 5.2.6 on 2025-10-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_order_total_price_alter_ticket_attendee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='ticket_price',
            field=models.FloatField(max_length=10),
        ),
    ]
