# Generated by Django 5.2.7 on 2025-10-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_orderitem_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('soon', 'Soon'), ('upcoming', 'Upcoming'), ('withheld', 'Withheld'), ('postponed', 'Postponed'), ('ongoing', 'Ongoing'), ('cancelled', 'Cancelled'), ('finished', 'Finished')], default='soon'),
        ),
    ]
