# Generated by Django 5.2.7 on 2025-10-15 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_event_event_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='order_status',
        ),
    ]
