# Generated by Django 5.2.7 on 2025-10-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_status_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
