# Generated by Django 5.2.7 on 2025-10-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_customuser_deleted_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
