# Generated by Django 5.2.7 on 2025-10-21 12:55

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', app.models.CustomUserManager()),
            ],
        ),
    ]
